import OpenAI from "openai";

export type BriefingInput = {
  name: string;
  title?: string | null;
  company?: string | null;
  email?: string | null;
  phone?: string | null;
  location?: string | null;
  tags?: string | null;
  howWeMet?: string | null;
  birthday?: string | null;
  customFields?: Record<string, string> | null;
  profile?: string | null;
  notes: { content: string; createdAt: Date | string }[];
};

export type BriefingResult = { briefing: string; model: string };

const SYSTEM_PROMPT = `You are a relationship-intelligence assistant helping someone prepare for a meeting.
Given structured contact details and notes, write a concise pre-meeting briefing.

Return GitHub-flavored markdown with these sections (omit a section entirely if there is nothing useful to say):

### Who They Are
One or two sentences — name, role, company, and how this relationship formed.

### Key Facts
A bullet list of notable facts: location, how they met, tags, upcoming birthday if within 30 days, and any standout custom fields.

### Recent Notes
A concise summary of the last few recorded interactions and observations.

### Open Follow-Ups
Any unresolved items, promises, or action items implied by the notes. If none are apparent, omit this section.

### Suggested Talking Points
3–4 specific conversation starters grounded in the notes and profile. Avoid generic openers.

Be concise. Ground every claim in the provided information. Do not invent facts.`;

export function buildUserMessage(input: BriefingInput): string {
  const fields = [
    ["Name", input.name],
    ["Title", input.title],
    ["Company", input.company],
    ["Location", input.location],
    ["Email", input.email],
    ["Phone", input.phone],
    ["Tags", input.tags],
    ["How we met", input.howWeMet],
    ["Birthday", input.birthday],
  ]
    .filter(([, v]) => v)
    .map(([k, v]) => `- ${k}: ${v}`)
    .join("\n");

  const custom = input.customFields
    ? Object.entries(input.customFields)
        .filter(([, v]) => v)
        .map(([k, v]) => `- ${k}: ${v}`)
        .join("\n")
    : "";

  const notes = input.notes.length
    ? input.notes
        .map((n, i) => {
          const date = new Date(n.createdAt).toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
            year: "numeric",
          });
          return `Note ${i + 1} (${date}): ${n.content}`;
        })
        .join("\n")
    : "(no notes yet)";

  const profileSection = input.profile
    ? `\nExisting relationship profile:\n${input.profile}`
    : "";

  return [
    `Contact details:\n${fields || "(none)"}`,
    custom ? `Additional info:\n${custom}` : "",
    profileSection,
    `Notes (most recent first):\n${notes}`,
  ]
    .filter(Boolean)
    .join("\n\n");
}

export function buildFallback(input: BriefingInput): string {
  const lines: string[] = [];

  lines.push("### Who They Are");
  const roleBits = [input.title, input.company && `at ${input.company}`]
    .filter(Boolean)
    .join(" ");
  const locationBit = input.location ? ` Based in ${input.location}.` : "";
  const metBit = input.howWeMet ? ` Met via: ${input.howWeMet}.` : "";
  lines.push(
    `${input.name}${roleBits ? ` — ${roleBits}` : ""}.${locationBit}${metBit}`
  );

  const facts: string[] = [];
  if (input.location) facts.push(`Location: ${input.location}`);
  if (input.howWeMet) facts.push(`How you met: ${input.howWeMet}`);
  if (input.tags) facts.push(`Tags: ${input.tags}`);
  if (input.customFields) {
    for (const [k, v] of Object.entries(input.customFields)) {
      if (v) facts.push(`${k}: ${v}`);
    }
  }
  if (facts.length) {
    lines.push("\n### Key Facts");
    for (const f of facts) lines.push(`- ${f}`);
  }

  if (input.notes.length) {
    lines.push("\n### Recent Notes");
    for (const n of input.notes.slice(0, 5)) lines.push(`- ${n.content}`);
  }

  lines.push("\n### Suggested Talking Points");
  if (input.company) lines.push(`- Ask about recent developments at ${input.company}.`);
  if (input.notes.length) lines.push("- Follow up on your most recent conversation.");
  lines.push("- Share something relevant you've come across since you last spoke.");
  lines.push("- Ask what they're currently focused on.");

  lines.push(
    "\n> _Generated by the local fallback profiler. Add an OPENAI_API_KEY to enable full AI briefings._"
  );

  return lines.join("\n");
}

export async function generateBriefing(
  input: BriefingInput
): Promise<BriefingResult> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return { briefing: buildFallback(input), model: "fallback" };
  }

  try {
    const client = new OpenAI({ apiKey });
    const model = process.env.OPENAI_MODEL || "gpt-4o-mini";
    const completion = await client.chat.completions.create({
      model,
      temperature: 0.4,
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: buildUserMessage(input) },
      ],
    });
    const text = completion.choices[0]?.message?.content?.trim();
    if (!text) return { briefing: buildFallback(input), model: "fallback" };
    return { briefing: text, model: completion.model || model };
  } catch (err) {
    console.error("OpenAI briefing generation failed, using fallback:", err);
    return { briefing: buildFallback(input), model: "fallback" };
  }
}
