import OpenAI from "openai";
import { fitNotesToBudget } from "@/lib/textBudget";

// Token budget for the concatenated notes block. gpt-4o-mini has a large
// context window; this keeps cost bounded while still covering a deep note
// history. Oldest notes are dropped first (see fitNotesToBudget).
const NOTES_TOKEN_BUDGET = 8000;

export type ProfileInput = {
  name: string;
  email?: string | null;
  phone?: string | null;
  company?: string | null;
  title?: string | null;
  location?: string | null;
  tags?: string | null;
  howWeMet?: string | null;
  notes: { content: string; createdAt: Date | string }[];
};

export type ProfileResult = {
  profile: string;
  model: string;
  // True when older notes were dropped to fit the token budget.
  notesTruncated: boolean;
  droppedNotes: number;
};

const SYSTEM_PROMPT = `You are Networky.ai's relationship-intelligence assistant.
Given structured contact details and freeform notes, write a concise, professional
relationship profile that helps the user maintain and leverage this connection.

Return GitHub-flavored markdown with these sections (omit a section if there is nothing useful to say):
### Summary
One or two sentences capturing who this person is and why they matter.
### Background
Role, company, expertise, and relevant professional context.
### Interests & Personal Notes
Personal details, interests, and anything useful for rapport (birthdays, family, hobbies).
### Opportunities
Concrete ways this person and the user could help each other (introductions, deals, collaborations).
### Suggested Follow-Ups
2-4 specific, actionable next steps.

Be specific and ground every claim in the provided information. Do not invent facts.`;

function buildUserMessage(input: ProfileInput): {
  message: string;
  notesTruncated: boolean;
  droppedNotes: number;
} {
  const fields = [
    ["Name", input.name],
    ["Title", input.title],
    ["Company", input.company],
    ["Location", input.location],
    ["Email", input.email],
    ["Phone", input.phone],
    ["Tags", input.tags],
    ["How we met", input.howWeMet],
  ]
    .filter(([, v]) => v)
    .map(([k, v]) => `- ${k}: ${v}`)
    .join("\n");

  // Cap the notes block to a token budget, keeping the most recent notes.
  const budgeted = fitNotesToBudget(input.notes, NOTES_TOKEN_BUDGET);
  let notes = budgeted.notes.length
    ? budgeted.notes.map((n, i) => `Note ${i + 1}: ${n.content}`).join("\n")
    : "(no notes yet)";
  if (budgeted.truncated) {
    notes = `(${budgeted.droppedCount} older note(s) omitted to fit length)\n${notes}`;
  }

  return {
    message: `Contact details:\n${fields || "(none)"}\n\nNotes:\n${notes}`,
    notesTruncated: budgeted.truncated,
    droppedNotes: budgeted.droppedCount,
  };
}

// Deterministic fallback so the feature is fully demonstrable without an API key.
function buildFallback(input: ProfileInput): string {
  const lines: string[] = [];
  lines.push("### Summary");
  const roleBits = [input.title, input.company && `at ${input.company}`]
    .filter(Boolean)
    .join(" ");
  lines.push(
    `${input.name}${roleBits ? ` — ${roleBits}` : ""}.${
      input.location ? ` Based in ${input.location}.` : ""
    }`
  );

  const background: string[] = [];
  if (input.title) background.push(`Works as ${input.title}.`);
  if (input.company) background.push(`Affiliated with ${input.company}.`);
  if (input.howWeMet) background.push(`Connection context: ${input.howWeMet}.`);
  if (background.length) {
    lines.push("\n### Background");
    lines.push(background.join(" "));
  }

  if (input.tags) {
    lines.push("\n### Interests & Personal Notes");
    lines.push(
      `Tags: ${input.tags
        .split(",")
        .map((t) => t.trim())
        .filter(Boolean)
        .join(", ")}.`
    );
  }

  if (input.notes.length) {
    lines.push("\n### Notes Captured");
    for (const n of input.notes) lines.push(`- ${n.content}`);
  }

  lines.push("\n### Suggested Follow-Ups");
  lines.push("- Send a short message to re-establish contact.");
  if (input.company)
    lines.push(`- Note any opportunities relevant to ${input.company}.`);
  lines.push("- Add a reminder to follow up within the next two weeks.");

  lines.push(
    "\n> _Generated by the local fallback profiler. Add an OPENAI_API_KEY to enable full AI profiles._"
  );
  return lines.join("\n");
}

export async function generateProfile(
  input: ProfileInput
): Promise<ProfileResult> {
  const { message, notesTruncated, droppedNotes } = buildUserMessage(input);

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return {
      profile: buildFallback(input),
      model: "fallback",
      notesTruncated,
      droppedNotes,
    };
  }

  try {
    const client = new OpenAI({ apiKey });
    const model = process.env.OPENAI_MODEL || "gpt-4o-mini";
    const completion = await client.chat.completions.create({
      model,
      temperature: 0.4,
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: message },
      ],
    });
    const text = completion.choices[0]?.message?.content?.trim();
    if (!text)
      return {
        profile: buildFallback(input),
        model: "fallback",
        notesTruncated,
        droppedNotes,
      };
    return {
      profile: text,
      model: completion.model || model,
      notesTruncated,
      droppedNotes,
    };
  } catch (err) {
    console.error("OpenAI profile generation failed, using fallback:", err);
    return {
      profile: buildFallback(input),
      model: "fallback",
      notesTruncated,
      droppedNotes,
    };
  }
}
